// <auto-generated />
using System;
using BackEnd.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEnd.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200521020455_bd")]
    partial class bd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BackEnd.Models.Atividade", b =>
                {
                    b.Property<int>("IdAtividade")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idAtividade")
                        .HasColumnType("int");

                    b.Property<string>("Atividade1")
                        .IsRequired()
                        .HasColumnName("atividade")
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnName("dataEntrega")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasColumnName("descricao")
                        .HasColumnType("text")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<int>("IdDisciplina")
                        .HasColumnType("int");

                    b.Property<string>("MoralAtividade")
                        .IsRequired()
                        .HasColumnType("varchar(45)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("Premiacao")
                        .IsRequired()
                        .HasColumnType("varchar(45)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("StatusAtividade")
                        .IsRequired()
                        .HasColumnName("statusAtividade")
                        .HasColumnType("enum('Pendente','Em andamento')")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("TipoAtividade")
                        .IsRequired()
                        .HasColumnName("tipoAtividade")
                        .HasColumnType("varchar(45)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<float>("Valor")
                        .HasColumnType("float");

                    b.HasKey("IdAtividade")
                        .HasName("PRIMARY");

                    b.HasIndex("IdDisciplina");

                    b.ToTable("atividade");
                });

            modelBuilder.Entity("BackEnd.Models.AtividadeUsuario", b =>
                {
                    b.Property<int>("IdAtividadeUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdAtividade")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioDisciplina")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Total")
                        .HasColumnType("double");

                    b.HasKey("IdAtividadeUsuario");

                    b.HasIndex("IdAtividade");

                    b.HasIndex("IdUsuarioDisciplina");

                    b.ToTable("AtividadeUsuario");
                });

            modelBuilder.Entity("BackEnd.Models.Disciplina", b =>
                {
                    b.Property<int>("IdDisciplina")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idDisciplina")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnName("descricao")
                        .HasColumnType("text")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasColumnName("materia")
                        .HasColumnType("varchar(35)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnName("turno")
                        .HasColumnType("varchar(20)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.HasKey("IdDisciplina")
                        .HasName("PRIMARY");

                    b.ToTable("disciplina");
                });

            modelBuilder.Entity("BackEnd.Models.Escola", b =>
                {
                    b.Property<string>("Cnpj")
                        .HasColumnName("cnpj")
                        .HasColumnType("varchar(20)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasColumnType("varchar(35)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnName("telefone")
                        .HasColumnType("varchar(25)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.HasKey("Cnpj")
                        .HasName("PRIMARY");

                    b.HasIndex("Telefone")
                        .IsUnique()
                        .HasName("telefone_UNIQUE");

                    b.ToTable("escola");
                });

            modelBuilder.Entity("BackEnd.Models.Usuario", b =>
                {
                    b.Property<string>("Cpf")
                        .HasColumnName("cpf")
                        .HasColumnType("varchar(20)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnName("dataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("varchar(90)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("EscolaCnpj")
                        .IsRequired()
                        .HasColumnName("escola_cnpj")
                        .HasColumnType("varchar(20)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("NomeSobrenome")
                        .IsRequired()
                        .HasColumnName("nomeSobrenome")
                        .HasColumnType("varchar(35)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnName("senha")
                        .HasColumnType("varchar(45)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("Telefone")
                        .HasColumnName("telefone")
                        .HasColumnType("varchar(25)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnName("tipoUsuario")
                        .HasColumnType("enum('Aluno','Professor','Responsavel','Adm')")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.HasKey("Cpf")
                        .HasName("PRIMARY");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasName("email_UNIQUE");

                    b.HasIndex("EscolaCnpj")
                        .HasName("fk_Usuario_Escola_idx");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("BackEnd.Models.UsuarioDisciplina", b =>
                {
                    b.Property<int>("IdUsuarioDisciplina")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idUsuario_Disciplina")
                        .HasColumnType("int");

                    b.Property<int>("DisciplinaIdDisciplina")
                        .HasColumnName("disciplina_idDisciplina")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCpf")
                        .IsRequired()
                        .HasColumnName("usuario_cpf")
                        .HasColumnType("varchar(20)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.HasKey("IdUsuarioDisciplina")
                        .HasName("PRIMARY");

                    b.HasIndex("DisciplinaIdDisciplina")
                        .HasName("fk_Usuario_has_Disciplina_Disciplina1_idx");

                    b.HasIndex("UsuarioCpf")
                        .HasName("fk_Usuario_has_Disciplina_Usuario1_idx");

                    b.ToTable("usuario_disciplina");
                });

            modelBuilder.Entity("BackEnd.Models.Atividade", b =>
                {
                    b.HasOne("BackEnd.Models.Disciplina", "Disciplina")
                        .WithMany("Atividades")
                        .HasForeignKey("IdDisciplina")
                        .HasConstraintName("fk_Disciplina_has_Atividade_Atividade1")
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Models.AtividadeUsuario", b =>
                {
                    b.HasOne("BackEnd.Models.Atividade", "IdAtividadeNavigation")
                        .WithMany("AtividadeUsuarioDisciplina")
                        .HasForeignKey("IdAtividade")
                        .HasConstraintName("fk_atividade_has_usuario_disciplina_atividade1")
                        .IsRequired();

                    b.HasOne("BackEnd.Models.UsuarioDisciplina", "IdUsuarioDisciplinaNavigation")
                        .WithMany("AtividadeUsuarioDisciplina")
                        .HasForeignKey("IdUsuarioDisciplina")
                        .HasConstraintName("fk_atividade_has_usuario_disciplina_usuario_disciplina1")
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Models.Usuario", b =>
                {
                    b.HasOne("BackEnd.Models.Escola", "EscolaCnpjNavigation")
                        .WithMany("Usuario")
                        .HasForeignKey("EscolaCnpj")
                        .HasConstraintName("fk_Usuario_Escola")
                        .IsRequired();
                });

            modelBuilder.Entity("BackEnd.Models.UsuarioDisciplina", b =>
                {
                    b.HasOne("BackEnd.Models.Disciplina", "DisciplinaIdDisciplinaNavigation")
                        .WithMany("UsuarioDisciplina")
                        .HasForeignKey("DisciplinaIdDisciplina")
                        .HasConstraintName("fk_Usuario_has_Disciplina_Disciplina1")
                        .IsRequired();

                    b.HasOne("BackEnd.Models.Usuario", "UsuarioCpfNavigation")
                        .WithMany("UsuarioDisciplina")
                        .HasForeignKey("UsuarioCpf")
                        .HasConstraintName("fk_Usuario_has_Disciplina_Usuario1")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
